name: Build and deploy ASP.Net Core app to Azure Web App - myDotnetWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/WebApp/WebApp.csproj

      - name: Build project
        run: dotnet build ./src/WebApp/WebApp.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./src/WebApp/WebApp.csproj -c Release -o publish_output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_62A167C610394FE3B26DF624B1672623 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B3052C057AEB4E209F9A8998695E40B5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_170B12FFFBE3476A9DC8B42474ABFB2E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myDotnetWebApp'
          slot-name: 'Production'
          package: .
